Interaction with ground
Zhehui-Huang/quad-swarm-rl pull request #25
Opened 2023-01-04 09:32 UTC by Mol2017

1. drone stops moving when height is less than 0.05
2. drone stops rotating and has a normal (0, 0, 1)

2023-01-04 21:24 UTC, Zhehui-Huang requested changes

2023-01-04 21:24 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +
Please remove this change.

2023-01-04 21:24 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_single.py
> +
Please remove this change.

2023-01-04 21:24 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_single.py
> +
Please remove this change.

2023-01-04 21:24 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_single.py
> +        if self.pos[2] <= 0.:
self.pos[2] should not be <=0.0, it should be <=0.05.

2023-01-04 21:24 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_single.py
> +                    self.vel[0:2] = 0.
If pos_z <0.05, should force pos_z = 0.05

2023-01-05 19:42 UTC, Mol2017 commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +
FIxed.

2023-01-05 19:42 UTC, Mol2017 commented on gym_art/quadrotor_multi/quadrotor_single.py
> +
Fixed

2023-01-05 19:42 UTC, Mol2017 commented on gym_art/quadrotor_multi/quadrotor_single.py
> +
Unused comments removed

2023-01-05 19:42 UTC, Mol2017 commented on gym_art/quadrotor_multi/quadrotor_single.py
> +        if self.pos[2] <= 0.:
Fixed

2023-01-05 19:44 UTC, Mol2017 commented on gym_art/quadrotor_multi/quadrotor_single.py
> +                    self.vel[0:2] = 0.
Fixed, position z is now clamped to [0.05, room_box limit].

2023-01-29 23:12 UTC, closed without merging