Obstacle removal
Zhehui-Huang/quad-swarm-rl pull request #33
Opened 2023-02-02 02:06 UTC by rahul-krupani

Ep_time removal

2023-02-02 03:21 UTC, Zhehui-Huang requested changes
Please check my comments. Besides, please also pull my latest commit as well. Use following command.

1) git remote add upstream    
 https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
 2) git fetch upstream
 3) git checkout BRANCH_NAME (This is branch on your side, for you, it is obstacle-removal)
4) git merge upstream/UPSTREAM_BRANCH_NAME (obstacle_design)

2023-02-02 03:21 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/octomap_creation.py
>                  y_gaussian_scale = self.y_gaussian_generation(regen_id=regen_id)
Why change this to 30?

2023-02-02 03:21 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +from gym_art.quadrotor_multi.scenarios.mix import create_scenario
Put create_scenario into utils.py

2023-02-02 03:21 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_single.py
> +import time
We didn't use `import time`

2023-02-02 23:23 UTC, rahul-krupani commented on gym_art/quadrotor_multi/octomap_creation.py
>                  y_gaussian_scale = self.y_gaussian_generation(regen_id=regen_id)
Was just debugging, fixed

2023-02-03 02:21 UTC, Zhehui-Huang approved these changes
Although there are still some issues in your PR, but not a big deal. I will change that for you.
For example, in mix.py, you need to remove all unused class. Please DO CLEAN your code next time before creating a PR.

2023-02-03 02:21 UTC, merged